- name: Install requirements
  apt: 
    name : "{{ item }}"
    update_cache: yes
  loop:
    - software-properties-common
    - apt-transport-https
    - debconf-utils
    - debconf
    - gnupg

- name: Add WebUpd8 team Oracle Java PPA
  apt_repository:
    repo: 'ppa:webupd8team/java'
    update_cache: yes

- name: Accept Oracle license
  debconf:
    name: oracle-java8-installer
    question: shared/accepted-oracle-license-v1-1
    value: 'true'
    vtype: select

- name: Install Oracle JDK 1.8
  apt:
    name: "{{ item }}"
  ignore_errors: "{{ ansible_check_mode }}"
  loop:
    - oracle-java8-set-default
    - oracle-java8-installer